name: CI

on:
  push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: 
          - lts/erbium
          - lts/fermium
          - lts/*
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm test
